
server:
  port: 80
  servlet:
    context-path: /

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true

spring:
  application:
    name: cloud-consumer-order-80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atguigu_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root



mybatis-plus:
  type-aliases-package: org.kirin.pojo
  global-config:
    db-config:
      id-type: auto #主键策略自增长
custom:
#  这个地方要写服务的名字，而不是服务的url，否则无法做负载均衡
  payment_url: "http://cloud-provider-payment/"